# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - name: always failure
      uses: cutenode/action-always-fail@v1.0.0
      
    - uses: actions/checkout@v3
      if: always()

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      if: always()
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      if: always()
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: run
      env: 
        CHAT_API_URL: ${{secrets.SYNOLOGY_CHAT_API_URL}}
        REPOSITORY: ${{github.event.repository.full_name}}
        MESSAGE: ${{github.event.head_commit.message}}
        MESSAGE_ID: ${{github.event.head_commit.message_id}}
        MESSAGE_URL: ${{github.event.head_commit.url}}
        TIMESTAMP: ${{github.event.head_commit.timestamp}}
        STATUS: 'success'
      run: |
        python test_bot.py "%CHAT_API_URL%" "%REPOSITORY%" "%MESSAGE%" "%MESSAGE_ID%" "%MESSAGE_URL%" "%TIMESTAMP%" "%STATUS%"


    - name: fail run
      shell: bash
      if: failure()
      env: 
        CHAT_API_URL: ${{secrets.SYNOLOGY_CHAT_API_URL}}
        REPOSITORY: ${{github.event.repository.full_name}}
        MESSAGE: ${{github.event.head_commit.message}}
        MESSAGE_ID: ${{github.event.head_commit.message_id}}
        MESSAGE_URL: ${{github.event.head_commit.url}}
        TIMESTAMP: ${{github.event.head_commit.timestamp}}
        STATUS: 'failure'
      run: |
        python test_bot.py ${{secrets.SYNOLOGY_CHAT_API_URL, github.event.repository.full_name}} ${{github.event.repository.full_name}} ${{github.event.head_commit.message}} ${{github.event.head_commit.message_id}} ${{github.event.head_commit.url}} ${{github.event.head_commit.timestamp}} failure
